#ifndef STUB_RETURNTYPES_H
#define STUB_RETURNTYPES_H

typedef enum {
    SPP_OK,
    SPP_ERROR,
    SPP_NOT_ENOUGH_PACKETS,
    SPP_NULL_PACKET,
    SPP_ERROR_ALREADY_INITIALIZED,
    SPP_ERROR_NULL_POINTER,
    SPP_ERROR_NOT_INITIALIZED,
    SPP_ERROR_INVALID_PARAMETER,
    SPP_ERROR_ON_SPI_TRANSACTION
} retval_t;

#endif
